const stitchTailwindConfig = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#f8f9fa",
        "surface-dim": "#d9dadb",
        "surface-bright": "#f8f9fa",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "surface-variant": "#e1e3e4",
        "surface-tint": "#5f5e5e",
        "on-surface": "#191c1d",
        "on-surface-variant": "#444748",
        background: "#f8f9fa",
        "on-background": "#191c1d",
        outline: "#747878",
        "outline-variant": "#c4c7c7",
        primary: "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1c1b1b",
        "on-primary-container": "#858383",
        "primary-fixed": "#e5e2e1",
        "primary-fixed-dim": "#c8c6c5",
        "on-primary-fixed": "#1c1b1b",
        "on-primary-fixed-variant": "#474746",
        secondary: "#bc000c",
        "on-secondary": "#ffffff",
        "secondary-container": "#e80f16",
        "on-secondary-container": "#fffbff",
        "secondary-fixed": "#ffdad5",
        "secondary-fixed-dim": "#ffb4aa",
        "on-secondary-fixed": "#410001",
        "on-secondary-fixed-variant": "#930007",
        tertiary: "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#001f2a",
        "on-tertiary-container": "#6b8896",
        "tertiary-fixed": "#c9e7f7",
        "tertiary-fixed-dim": "#adcbda",
        "on-tertiary-fixed": "#001f2a",
        "on-tertiary-fixed-variant": "#2e4b57",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f2",
        "inverse-primary": "#c8c6c5",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        card: "24px",
        btn: "8px",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        "container-max": "1280px",
        gutter: "24px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "section-gap": "80px",
      },
      fontFamily: {
        "display-lg": ["Manrope"],
        "display-lg-mobile": ["Manrope"],
        "headline-lg": ["Manrope"],
        "headline-lg-mobile": ["Manrope"],
        "headline-md": ["Manrope"],
        "body-lg": ["Manrope"],
        "body-md": ["Manrope"],
        "label-md": ["Manrope"],
        "label-sm": ["Manrope"],
      },
      fontSize: {
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "display-lg-mobile": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
    },
  },
};

window.tailwind = window.tailwind || {};
window.tailwind.config = stitchTailwindConfig;

if (typeof tailwind !== "undefined") {
  tailwind.config = stitchTailwindConfig;
}
